[package]
name = "composer-parser"
description = "Parses the JSON output of composer outdated"
readme = "README.md"
license = "MIT/Apache-2.0"
version = "0.1.3"
authors = ["Matthias Hörmann <mhoermann@gmail.com>"]
edition = "2021"
repository = "https://github.com/taladar/composer-parser"
categories = [ "parser-implementations" ]
keywords = [ "composer", "composer-outdated", "php" ]

exclude = [ ".env", "tarpaulin-report.html", "tarpaulin-report.json" ]

[profile.release]
# do not strip debug info from release builds, useful for debugging those, cargo-flamegraph profiling or similar use cases
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.thiserror]
version = "~1.0"

[dependencies.tracing]
version = "~0.1"

[dependencies.clap]
version = "~3.1"
features = ["derive", "cargo"]

[dependencies.serde]
version = "~1.0"
features = ["derive"]

[dependencies.serde_json]
version = "~1.0"

[dev-dependencies.pretty_assertions]
version = "~1.0"
